### ISSUE TITLE
Botón Sign in/up en inglés

### ISSUE THREAD

**Issue by richhl** [isiargonauta/humhub#3]
Para reproducir en una instalación limpia en que se indica idioma español al entrar a http://machine/humhub aparece Sign in/up en inglés

![captura de pantalla de 2016-06-30 14 25 23](https://cloud.githubusercontent.com/assets/1074446/16488034/aaa3ba02-3ece-11e6-9498-4362eba37def.png)

**Comment by infodima** [comment]
solucionado
